# Generated by Django 5.0.4 on 2024-05-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property_details',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('property_price', models.FloatField()),
                ('property_area', models.FloatField()),
                ('property_location', models.CharField(max_length=100)),
                ('property_description', models.TextField()),
                ('property_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
