# Generated by Django 5.0.4 on 2024-05-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_additional_info_table',
            fields=[
                ('additional_info_table', models.AutoField(primary_key=True, serialize=False)),
                ('additional_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='property_agent_table',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_email', models.EmailField(max_length=254)),
                ('agent_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='property_amenity_table',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='property_features_table',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='property_location_table',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighborhood', models.CharField(max_length=100)),
                ('nearbyamenities', models.TextField()),
                ('distancetocitycenter', models.FloatField()),
                ('publictransport', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='property_media_table',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(max_length=100)),
                ('media_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='property_table',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=100)),
                ('property_adress', models.CharField(max_length=100)),
                ('propert_type', models.CharField(max_length=100)),
                ('property_bathrooms', models.IntegerField()),
                ('property_square_feet', models.FloatField()),
                ('property_description', models.TextField()),
                ('property_buying_price', models.FloatField()),
                ('property_renting_price', models.FloatField()),
                ('property_hoafees', models.FloatField()),
                ('property_availability', models.BooleanField()),
                ('property_lastupdatedate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='property_details',
        ),
        migrations.AddField(
            model_name='property_media_table',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.property_table'),
        ),
        migrations.AddField(
            model_name='property_location_table',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.property_table'),
        ),
        migrations.AddField(
            model_name='property_features_table',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.property_table'),
        ),
        migrations.AddField(
            model_name='property_amenity_table',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.property_table'),
        ),
        migrations.AddField(
            model_name='property_agent_table',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.property_table'),
        ),
        migrations.AddField(
            model_name='property_additional_info_table',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.property_table'),
        ),
    ]
