# Generated by Django 5.0.4 on 2024-05-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_users_delete_admins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
